### ISSUE TITLE
Use CUDA-12.4 to build the porject instead of CUDA-12.1?

### ISSUE THREAD

**Issue by xmfbit** [mit-han-lab/nunchaku#15]
When I first started trying to compile this project, I found that the guide provided a torch version with cuda12.1, so I used a docker image with cuda 12.1. However, I kept encountering the following errors:

```
/home/me/nunchaku/third_party/spdlog/include/spdlog/fmt/bundled/format.h(4449): error: a literal operator template must have a template parameter list equivalent to "<char ...>"
  template <detail_exported::fixed_string Str> constexpr auto operator""_a() {
                                                              ^

/home/me/nunchaku/src/common.h(41): error: call to consteval function "std::source_location::current" did not produce a valid constant expression
  inline cudaError_t checkCUDA(cudaError_t retValue, const std::source_location location = std::source_location::current()) {
```

It wasn't until I set `export CUDA_HOME=/usr/local/cuda-12.4` that I was able to compile it successfully. Moreover, the compiled product can be used with torch 2.4.1+cu121.

So, I would like to confirm, did you also use CUDA-12.4 when compiling?

**Comment by sxtyzhangzk** [comment]
We tested our code using CUDA 12.2/12.6 on Linux and 12.6 on Windows. 12.4 on Linux should also be OK.

**Comment by xmfbit** [comment]
ok, from your response, I understand that you also did not compile with CUDA 12.1. Would you consider revising the installation instructions for torch in the README, to avoid confusion for others? Debugging the compilation error is really terrible.

```
# maybe remove cuda12.1 is better
pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121
```

**Comment by kelisiya** [comment]
> We tested our code using CUDA 12.2/12.6 on Linux and 12.6 on Windows. 12.4 on Linux should also be OK.

Build cuda_12.6.r12.6/compiler.34431801_0 , when I run the example , 
`RuntimeError: CUDA error: no kernel image is available for execution on the device (at /app/src/kernels/awq/gemv_awq.cu:311)`

**Comment by xmfbit** [comment]
@kelisiya make sure the arch of your gpu device is `sm_86` or `sm_89`: https://github.com/mit-han-lab/nunchaku/blob/main/setup.py#L56-L57
